# Generated by Django 4.0.2 on 2022-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_Libro', models.CharField(max_length=300, verbose_name='Titulo_Libro')),
                ('Apunte', models.TextField(null=True, verbose_name='Apunte')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('Autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('Numero_Paginas', models.IntegerField(verbose_name='N_Paginas')),
                ('Genero', models.CharField(max_length=500, verbose_name='Genero')),
                ('Leido', models.BooleanField(verbose_name='Leido')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Img_Books')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_Libro', models.CharField(max_length=300, verbose_name='Titulo_libro')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Img_Books_Wish_List')),
            ],
        ),
    ]
