# Generated by Django 4.0.2 on 2022-04-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Book',
        ),
        migrations.RemoveField(
            model_name='importantpoints',
            name='Titulo_Libro',
        ),
    ]
