# Generated by Django 4.0.2 on 2022-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0004_alter_wishlist_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='Precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
